/*     ___    ____  __    ___   _________
 *    /   |  / _  |/ /   / / | / /__  __/          Source Code Static Analyzer
 *   / /| | / / / / /   / /  |/ /  / /                  AdLint - Advanced Lint
 *  / __  |/ /_/ / /___/ / /|  /  / /
 * /_/  |_|_____/_____/_/_/ |_/  /_/  Copyright (C) 2010-2014, OGIS-RI Co.,Ltd.
 *
 * Project specific initial header file generated by adlintize 3.2.14
 * at 2016-08-17 13:50:37 +0500.
 */

/* Put project specific predefined macros and types here. */
