/*     ___    ____  __    ___   _________
 *    /   |  / _  |/ /   / / | / /__  __/          Source Code Static Analyzer
 *   / /| | / / / / /   / /  |/ /  / /                  AdLint - Advanced Lint
 *  / __  |/ /_/ / /___/ / /|  /  / /
 * /_/  |_|_____/_____/_/_/ |_/  /_/  Copyright (C) 2010-2012, OGIS-RI Co.,Ltd.
 *
 * Compiler specific initial header file generated by adlintize 1.10.0
 * at 2016-08-16 16:38:10 +0500.
 */

/* Put compiler specific predefined macros and types here. */

//#define __const const
//#define __restrict restrict
//#define __inline inline
typedef  void * __builtin_va_list;
#define __builtin_va_start(a, b) ((void)a)
#define __builtin_va_end(a) ((void)a)
#define __builtin_va_arg(ar, t) ((void)ar)
#define __builtin_va_copy(d, s) ((void)d)
//#define __builtin_offsetof(type, member) (0)
//#define __alignof__(type) (0)
